# Generated by Django 3.1.7 on 2021-03-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('capital', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=40)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
